language: java
jdk:
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
env:
  global:
  # GRADLE_KEY
  - secure: "wh7Ynt7eu5zcpL4gDtEOBydfyOGyj03AU9ZB8NYsGCB6dQ2K9dGjPvogZPY/9gEo4l0Uo/hxUjoMSIdqhFaHpXFkQ+UMwrEZQXlFi4lfTE9MyUph+3b+55bm85wO7SMF5eWFZ0rLGQ5qEVPao+u8vSbhSbqvmAUhuLOFhnTHpUzWDQCEA50xh01SysR7jBMWu2uX7pgrGJrOVR+ffxkTF3ZXXrWJiqaRrAAkOqXZqoNKx0fuU1aP/JR+vJHCspPZYc8fCR+X8rsTJkjLJCsayT3DEnwba4nGBVKoWU36ltGBVVbgLisEwp6luTcLcREtPG3TPwz4dv/OwDYIAIjQI3dy+jWhcwSpJmTSLjDU8v90v0adnejDW6vruwxYV8pCygtWbBToHBzLAO/0a7Wgn0DZycJjwrg5w5CAGkOTLPvgMN+GudxXG95PGRzEUKMyRbVRFGX5pMlun9/e6+1cT5iYihoyIsDaJxkMtV3NcRH4r1O9NtffRE1OrSs9UDcR1bh8TKUGMlt7d8ic3YBXKLKXTCge7Iw5Tv9F64vhszjLBwD2ykMS+eTP38mTG0eMxE7nmRU7VY0eYqu1ii6UTnCufzEWuHqV7CMoYQxU2oHxE/1rpuwrGnP4YGokzUNjaz022ohg4qv1LHwqSMMrC3lArOies+6EOyR12/oiyu0="
  # GRADLE_SECRET
  - secure: "QxlgabB747DVcRND1Zx0FZHGIXdx6t6NmkwhTTgeb1+0SQq1fnI26aiWjQosN6TOwoi2g4kXzl6RJYss6YrO7A/iQ0vVxrKexTgd2ZTBqT8S5MrRgCes/5dPKLRcvzsyzHedExEgld/Wj9RCISA7uSv+EOzFHeklN1mEEc8kEeG8rJqlsmSmxnbMiOSR4ymOcQ9nibfzaKu483p7HLBDrJgUtXQVvxFXuJLiIUfAChnltN05crmpa215D0gTUzBBuRTf+LxoEMaCWH8CWRPZENGs4XTH4vRJrnhVEoCyMRgII6ruS/LvQpRY8ZRuUGNhuyP2F40bed8yUCDmaZU2PVQ8K/Voqu7TovUeEhOIfEbI0vh7vU9cttQ5xAdHr3wixcILgl9RCzb2vdEHHNjbDe/+eNSpDb2uZZrMUfwhE9ptyISamEiRr5ZqSFLi30SW4C63IBEdtk3RUl4yF3FxAfpergUjJxFPQgV1ve80c8BKBpd7kqqB15lEPgvQBj/rXE2/KMFirNEvM6eJCf+LyOnnpuwe+9xatqeRqyAm1mczJiWLWGAD3/5UBTt3w6A921Rx1na7MA7TaOQqRftThjSAD/wqEjAMlZaxpGwO1y3xfSdMld9mZb0oTGsGBcrxpgAaeKqdWeUNcQy4p/xpMu2PZQbocEJ/hmOdgNErcVM="

before_script:
  - mkdir -p ~/.gradle/
  - echo gradle.publish.key=${GRADLE_KEY} >> ~/.gradle/gradle.properties
  - echo gradle.publish.secret=${GRADLE_SECRET} >> ~/.gradle/gradle.properties

script:
  - ./gradlew --daemon
  - ./gradlew build -x test
  - ./gradlew test

deploy:
  provider: script
  script: bash publish.sh
  on:
    tags: true
