name: test-deploy-gradle-sora-plugin
on: [push]
jobs:
  test-deploy-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Store gradle key & secret into gradle.properties
        env:
          GRADLE_KEY: ${{ secrets.GRADLE_KEY }}
          GRADLE_SECRET: ${{ secrets.GRADLE_SECRET }}
        run: |
          mkdir -p ~/.gradle/
          touch ~/.gradle/gradle.properties
          echo gradle.publish.key=${GRADLE_KEY} >> ~/.gradle/gradle.properties
          echo gradle.publish.secret=${GRADLE_SECRET} >> ~/.gradle/gradle.properties
          
      - name: print current working directory
        run: |
          pwd
          ls
          ls -al
          ls -al ..
          ls -al ../../
          ls -al ../../../
          ls -al ../../../../
          ls -al ../../../../../

      - name: make scripts executable
        run: |
          chmod +x gradlew
          chmod +x publish.sh
        
      - name: old run
        run: |
          ./gradlew --daemon
          ./gradlew build -x test
          ./gradlew test
      
      - name: Run Deployment Script
        run: ./publish.sh
        shell: bash
