name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Store gradle key & secret into gradle.properties
        env:
          GRADLE_KEY: ${{ secrets.GRADLE_KEY }}
          GRADLE_SECRET: ${{ secrets.GRADLE_SECRET }}
        run:
          mkdir -p ~/.gradle/
          echo gradle.publish.key=${GRADLE_KEY} >> ~/.gradle/gradle.properties
          echo gradle.publish.secret=${GRADLE_SECRET} >> ~/.gradle/gradle.properties

      - name: Run Gradle Wrapper Daemon, Build, and Test
        run:
          ./gradlew --daemon
          ./gradlew build -x test
          ./gradlew test
      
      - name: Run Deployment Script
        run: ./publish.sh
        shell: bash
